

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#LIBRARIES
suppressMessages(library(openintro))
suppressMessages(library(MASS))
suppressMessages(library(tidyverse))
suppressMessages(library(statmod))
suppressMessages(library(ggplot2))
suppressMessages(library(reshape2))
suppressMessages(library(car))
suppressMessages(library(knitr))
```

```{r}
set.seed(123)
```


```{r}
# Import the dataset
source("http://www.openintro.org/stat/data/cdc.R")
```

```{r}
#EDA
#weight you want to lose
cdc$wtchange<-cdc$weight-cdc$wtdesire
#Dimension of data
dim(cdc)
# View the first few rows of the dataset
head(cdc)

# Find missing values in each column
missing_count <- sapply(cdc, function(x) sum(is.na(x)))
# Display the count of missing values in each column
print(missing_count)


```


```{r}
library(ggplot2)
library(gridExtra)


#EDA
# Boxplot of age
g1<-ggplot(cdc, aes(x = age)) +
  geom_boxplot( fill = "blue", color = "black") +
  labs(title = "Figure 1.1:Histogram of Age", x = "Age")



# Boxplot of weightchange
g2<-ggplot(cdc, aes(x = wtchange)) +
  geom_boxplot( fill = "tomato", color = "black") +
  labs(title = "Figure 1.2 :Histogram of Desired Weight Loss", x = "Change in Weight")


# Create a bar plot for by whether the respondent had smoked at least 100 cigarettes


# Create a ggplot barplot for health coverage
g3<- ggplot(frequency_table, aes(x = reorder(hlthplan, n), y = n)) +
  geom_bar(stat = "identity", fill = "lightgreen") +
  labs(x = "Health Coverage", y = "Frequency", title = "Figure 1.3 Distribution of Health Coverage") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels for readability





# Histogram of  weight change (wtchange) by exercise status (exerany)
g4<-ggplot(cdc, aes(x = wtchange, fill = factor(exerany))) +
  geom_histogram(binwidth = 10, position = "dodge") +
  labs(title = "Figure 1.4: Weight Change by Exercise Status",
       x = "Weight Change (lbs)",
       y = "Frequency") +
  scale_fill_manual(values = c("1" = "violet", "0" = "purple")) +
  theme_minimal()+
  coord_cartesian(xlim = c(-200, 200),ylim = c(0, 1500))

# Arrange the ggplots in a 2x2 grid
grid.arrange(g1,g2,g3,g4, ncol = 2)


#par(mfrow = c(3, 4))
#EDA
# Boxplot of age
ggplot(cdc, aes(x = age)) +
  geom_boxplot( fill = "blue", color = "black") +
  labs(title = "Figure 1.1:Histogram of Age", x = "Age")
hist(cdc$age,main="age")

# Boxplot of height
ggplot(cdc, aes(x = height)) +
  geom_boxplot( fill = "red", color = "black") +
  labs(title = "Histogram of Height", x = "Height")
hist(cdc$height,main="height")

# Remove outliers from weight change
cdc <- subset( cdc, height<90)

# Boxplot of height
#ggplot(cdc, aes(x = height)) +  geom_boxplot( fill = "red", color = "black") +  labs(title = "Histogram of Height", x = "Height")

# Boxplot of weight
ggplot(cdc, aes(x = weight)) +
  geom_boxplot( fill = "yellow", color = "black") +
  labs(title = "Histogram of Weight", x = "Weight")

hist(cdc$weight,main="weight",xlim = c(50, 450))

# Remove outliers from weight 
cdc <- subset( cdc,  weight < 450)

# Boxplot of weight
#ggplot(cdc, aes(x = weight)) +  geom_boxplot( fill = "yellow", color = "black") +labs(title = "Histogram of Weight", x = "Weight")

# Boxplot of weightchange
ggplot(cdc, aes(x = wtchange)) +
  geom_boxplot( fill = "blue", color = "black") +
  labs(title = "Figure 1.3 Histogram of Desired Weight Loss", x = "Change in Weight")
hist(cdc$wtchange,main="wtchange",xlim = c(-50, 250))

 #Remove outliers from weight change
cdc <- subset( cdc, wtchange > -200 & wtchange < 280)

# Boxplot of weight
#ggplot(cdc, aes(x = wtchange)) +  geom_boxplot( fill = "blue", color = "black") +  labs(title = "Histogram of Weight", x = "Change in Weight")

# Create a bar plot for by whether the respondent had smoked at least 100 cigarettes
barplot(table(cdc$smoke100), col = "lightblue", main = " Distribution ofwhether the respondent had smoked at least 100 cigarettes or not ")

# Create a bar plot for by whether the respondent had smoked at least 100 cigarettes
barplot(table(cdc$hlthplan), col = "lightgreen", main = "Figure 2.3: Distribution of Health Coverage")

# Create a bar plot for Gender
barplot(table(cdc$gender), col = "orange", main = " Distribution of Gender")

# Table for General Health
#genhlth <-table(cdc_train$genhlth)
knitr::kable(table(cdc$genhlth), 
      caption = "General Health Distribution")

# Histogram of  weight change (wtchange) by exercise status (exerany)
hist(cdc$wtchange[cdc$exerany == 1], col = "violet", main = " Figure 2.4:Weight change by Exercise Status", xlab = " Weight Change (lbs)")
hist(cdc$wtchange[cdc$exerany == 0], col = "purple", add = TRUE)
legend("topright", legend = c("Exercise", "No Exercise"), fill = c("violet", "purple"))

cdc<-na.omit(cdc)
dim(cdc)


```


```{r}

# Split data into 80% training and 20% test set
# Split the data into 80% training and 20%testing sets 
train_sample <- sample(1:nrow(cdc), 0.8*nrow(cdc), replace = F)
cdc_train <- cdc[train_sample,]

cdc_test <- cdc[setdiff(1:nrow(cdc), train_sample),]
nrow(cdc_test)
nrow(cdc_train)


```

```{r}
emplogitPlot <- function(x, y, binsize = NULL, ci = FALSE, probit = FALSE,
prob = FALSE, main = NULL, xlab = "", ylab = "", lowess.in = FALSE){
  # x         vector with values of the independent variable
  # y         vector of binary responses
  # binsize   integer value specifying bin size (optional)
  # ci        logical value indicating whether to plot approximate
  #           confidence intervals (not supported as of 02/08/2015)
  # probit    logical value indicating whether to plot probits instead
  #           of logits
  # prob      logical value indicating whether to plot probabilities
  #           without transforming
  #
  # the rest are the familiar plotting options
  
  if(class(y) =="character"){
   y <- as.numeric(as.factor(y))-1
   }
  
  if (length(x) != length(y))
    stop("x and y lengths differ")
  if (any(y < 0 | y > 1))
    stop("y not between 0 and 1")
  if (length(x) < 100 & is.null(binsize))
    stop("Less than 100 observations: specify binsize manually")
  
  if (is.null(binsize)) binsize = min(round(length(x)/10), 50)
  
  if (probit){
    link = qnorm
    if (is.null(main)) main = "Empirical probits"
  } else {
    link = function(x) log(x/(1-x))
    if (is.null(main)) main = "Empirical logits"
  }
  
  sort = order(x)
  x = x[sort]
  y = y[sort]
  a = seq(1, length(x), by=binsize)
  b = c(a[-1] - 1, length(x))
  
  prob = xmean = ns = rep(0, length(a)) # ns is for CIs
  for (i in 1:length(a)){
    range = (a[i]):(b[i])
    prob[i] = mean(y[range])
    xmean[i] = mean(x[range])
    ns[i] = b[i] - a[i] + 1 # for CI 
  }
  
  extreme = (prob == 1 | prob == 0)
  prob[prob == 0] = min(prob[!extreme])
  prob[prob == 1] = max(prob[!extreme])
  
  g = link(prob) # logits (or probits if probit == TRUE)
  
  linear.fit = lm(g[!extreme] ~ xmean[!extreme])
  b0 = linear.fit$coef[1]
  b1 = linear.fit$coef[2]
  
  loess.fit = loess(g[!extreme] ~ xmean[!extreme])
  
  plot(xmean, g, main=main, xlab=xlab, ylab=ylab)
  abline(b0,b1)
  if(lowess.in ==TRUE){
  lines(loess.fit$x, loess.fit$fitted, lwd=2, lty=2)
  }
}
```



```{r}
par(mfrow = c(2,1))
emplogitPlot(x=cdc_train$wtchange , y=cdc_train$exerany, 
             xlab = "Weight change(Pounds)", 
             ylab = "log odds of Exercising regularly", 
             main = "Figure 1.5")

emplogitPlot(x=cdc_train$age , y=cdc_train$exerany, 
             xlab = "Age(Years)", 
             ylab = "log odds of Exercising regularly", 
             main = "Figure 1.6")



```

```{r}
par(mfrow = c(2, 1))
emplogitPlot(x=cdc_train$weight , y=cdc_train$exerany, 
             xlab = "Weight(lbs)", 
             ylab = "log odds of Exercising regularly", 
             main = "Figure 1")




emplogitPlot(x=cdc_train$height , y=cdc_train$exerany, 
             xlab = "Height(inches)", 
             ylab = "log odds of Exercising regularly", 
             main = "Figure 1")







```

```{r}
MODEL1<-glm(exerany~wtchange+age+genhlth+hlthplan,data=cdc_train, family = "binomial")
summary(MODEL1)$coefficients

```


```{r}
#Model Diagnostics

b1<-data.frame(x = cdc_train$wtchange, residuals = qresid(MODEL1)) %>%
ggplot(aes(x = x, y = residuals)) +
geom_point() +
geom_smooth() +
theme_bw() +
xlab("Weight Change") +
ylab("Quantile residuals") +
ggtitle("Figure 1.7: Quantile Residuals for Desired weight loss")


b2<-data.frame(x = sqrt(cdc_train$wtchange), residuals = qresid(MODEL1)) %>%
ggplot(aes(x = x, y = residuals)) +
geom_point() +
geom_smooth() +
theme_bw() +
xlab("Square root of Weight Change") +
ylab("Quantile residuals") +
ggtitle(" Figure 1.8: Quantile Residuals forsqaure root of  Desired weight loss")

b3<-data.frame(x = cdc_train$age, residuals = qresid(MODEL1)) %>%
ggplot(aes(x = x, y = residuals)) +
geom_point() +
geom_smooth() +
theme_bw() +
xlab("Age") +
ylab("Quantile residuals") +
ggtitle("Figure 1.9: Quantile Residuals for age")

# Arrange the ggplots in a 2x2 grid
grid.arrange(b1,b2,b3, ncol = 2)
```

```{r}

d1<-data.frame(x = cdc_train$weight, residuals = qresid(MODEL1)) %>%
ggplot(aes(x = x, y = residuals)) +
geom_point() +
geom_smooth() +
theme_bw() +
xlab("Weight") +
ylab("Quantile residuals")+
ggtitle("Figure 1.9: Quantile Residuals for weight")




d2<-data.frame(x = cdc_train$height, residuals = qresid(MODEL1)) %>%
ggplot(aes(x = x, y = residuals)) +
geom_point() +
geom_smooth() +
theme_bw() +
xlab("Height") +
ylab("Quantile residuals")+
ggtitle("Figure 1.9: Quantile Residuals for height")


# Arrange the ggplots in a 2x1 grid
grid.arrange(d1,d2, ncol = 1)

```




```{r}

# Cook"s distance
par(mfrow = c(2, 2))

plot(cdc_train$wtchange, cooks.distance(MODEL1),main="Figure 1.10 : Cooks distance for desired weight loss")
plot(cdc_train$hlthplan, cooks.distance(MODEL1),main="Figure 1.11 : Cooks distance for health coverage")
plot(cdc_train$genhlth, cooks.distance(MODEL1),main="Figure 1.12 : Cooks distance for general health")
plot(cdc_train$age, cooks.distance(MODEL1),main="Figure 1.13 : Cooks distance for age")

```




```{r}
#VIF
vif(MODEL1)
```



```{r}
MODEL2<-glm(exerany~sqrt(wtchange)+age+genhlth+hlthplan,data=cdc_train, family = "binomial")
summary(MODEL2)$coefficients
```
F

```{r}
#dengue <- read.csv("https://sta712-f22.github.io/homework/dengue.csv")

# specify the starting model (intercept-only)
m0 <- glm(exerany ~ 1, data = cdc_train, family = binomial)

# forward selection using AIC
# Note we have to specify the largest model we want to consider
forward_aic <- stepAIC(m0, scope = ~  hlthplan+smoke100+height+ wtchange+age+gender+weight ,
                      direction = "forward",
                      trace = 0)

summary(forward_aic)
```


```{r}
# forward selection using BIC
# Note we have to specify the largest model we want to consider
# k = log(n) is used to specify the penalty for BIC instead of AIC
forward_bic <- stepAIC(m0, scope = ~  hlthplan+smoke100+height+ weight+age+gender+wtchange ,
                      direction = "forward",
                      trace = 0, k = log(nrow(cdc)))

summary(forward_bic)
```



```{r}
#m1 <- glm(Survived ~ Sex + Age + Pclass, data = titanic, family = binomial)

 table("Predicted" = ifelse(forward_bic$fitted.values > 0.5, 1, 0),
 "Observed" = forward_bic$y)

```

Table 1.8 shows the sensitivity, specificity and accuracy of our model.

```{r}
Sensitiivity=11868/(79+11868)
Specificity=88/(88+3961)
Accuracy=(11868+88)/(79+11868+88+3961)
Sensitiivity
Specificity
Accuracy

```



```{r}




## TPR vs. FPR for model 1
pred1 <- prediction(forward_bic$fitted.values, forward_bic$y)
perf1 <- performance(pred1,"tpr","fpr")

# Plot ROC curve for Model 
ggplot(aes(x = fpr, y = tpr, color = "Model"),data = data.frame(fpr = perf1@x.values[[1]], tpr = perf1@y.values[[1]])) +
  geom_line() +
  geom_abline(slope = 1, intercept = 0, linetype = 2) +
  labs(x = "False positive rate (1 - Specificity)", y = "True positive rate (Sensitivity)",
       title = "Figure 1.14: ROC Curve ")


## calculate AUC values
performance(pred1, "auc")@y.values # AUC for model 1


```













